apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
sepc:
  replicas: 1
  selector: 
    matchLabels:
      app: posts
  template: 
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: hammadali/posts:0.0.1